### PR TITLE
Stable version

### LINKED ISSUE #33: Confidence intervals from each universe
Related to #9 
Allow the user to extract point estimates and confidence intervals for a particular variable from each universe

### PR DESCRIPTION
**Pull request by abhsarma**
Fixes #33, #34, #35 and #42

### CODE REVIEW

**Comment by abhsarma** [comment]
Also fixes #37

**Comment by mjskay** [comment]
Awesome!

Question re: patchwork: is there anything you're using it for that you can't do using cowplot::plotgrid()? Patchwork has been pre-CRAN for a long time and its last commit on github was almost a year ago. CRAN doesn't like non-CRAN dependencies, so gambling on patchwork going to CRAN before we do may not be the best bet.

**Comment by abhsarma** [comment]
I found aligning margins in cowplot to be a pain:

Screen Shot 2019-08-06 at 11 14 36 AM


Whereas patchwork gives me this:

Screen Shot 2019-08-06 at 11 15 10 AM

But I guess I should be able to figure out how to do it in cowplot. It's probably worth the trade-off

**Comment by mjskay** [comment]
You can use the `align` parameter of `plot_grid()` to do it

**Pull request merged**
